
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateEventEmitterH.js
 */
#pragma once

#include <react/renderer/components/view/ViewEventEmitter.h>
#include <jsi/jsi.h>

namespace facebook {
namespace react {
class JSI_EXPORT RNCPickerViewEventEmitter : public ViewEventEmitter {
 public:
  using ViewEventEmitter::ViewEventEmitter;
    struct OnPicker {
        std::string value;
        int index;
    };
  
    void onPickerConfirm(OnPicker value) const;
    void onPickerCancel(OnPicker value) const;
    void onPickerSelect(OnPicker value) const;
};
} // namespace react
} // namespace facebook
