
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateEventEmitterCpp.js
 */

#include "EventEmitters.h"


namespace facebook {
namespace react {
void RNCPickerViewEventEmitter::onPickerConfirm(OnPicker event) const
{
    dispatchEvent("pickerConfirm", [event = std::move(event)](jsi::Runtime &runtime) {
        auto payload = jsi::Object(runtime);
        payload.setProperty(runtime, "value", event.value);
        payload.setProperty(runtime, "index", event.index);
        return payload;
    });
}
void RNCPickerViewEventEmitter::onPickerCancel(OnPicker event) const
{
    dispatchEvent("pickerCancel", [event = std::move(event)](jsi::Runtime &runtime) {
        auto payload = jsi::Object(runtime);
        payload.setProperty(runtime, "value", event.value);
        payload.setProperty(runtime, "index", event.index);
        return payload;
    });
}
void RNCPickerViewEventEmitter::onPickerSelect(OnPicker event) const
{
    dispatchEvent("pickerSelect", [event = std::move(event)](jsi::Runtime &runtime) {
        auto payload = jsi::Object(runtime);
        payload.setProperty(runtime, "value", event.value);
        payload.setProperty(runtime, "index", event.index);
        return payload;
    });
}
} // namespace react
} // namespace facebook
