
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GeneratePropsH.js
 */
#pragma once

#include <react/renderer/components/view/ViewProps.h>
#include <react/renderer/core/PropsParserContext.h>

namespace facebook {
    namespace react {

        class RNCPickerViewProps final : public ViewProps {
        public:
            RNCPickerViewProps() = default;
            RNCPickerViewProps(const PropsParserContext &context, const RNCPickerViewProps &sourceProps,
                               const RawProps &rawProps);

#pragma mark - Props
            bool isLoop{false};

            std::string pickerConfirmBtnText{};
            std::string pickerCancelBtnText{};
            std::string pickerTitleText{};
            std::string pickerFontFamily{};
            int pickerTextEllipsisLen{0};
            folly::dynamic pickerConfirmBtnColor{};
            folly::dynamic pickerCancelBtnColor{};
            folly::dynamic pickerTitleColor{};
            folly::dynamic pickerToolBarBg{};
            folly::dynamic pickerBg{};
            int pickerToolBarFontSize{0};
            folly::dynamic wheelFlex{};
            int pickerFontSize{0};
            folly::dynamic pickerFontColor{};
            int pickerRowHeight{0};
            folly::dynamic pickerData{};
            folly::dynamic selectedValue{};
        };

    } // namespace react
} // namespace facebook
